In [1]:
%load_ext autoreload
%autoreload 2

import os, sys, itertools
from pathlib import Path
sys.path.append('..')

import torch
from torch import nn, optim
from torch.nn import functional as F

#from PreTrainedFIM.model import VGG16_FIM, VGG16bn_FIM
from PreTrainedFIM.repara_model import VGG16bn_FIM
from PreTrainedFIM.util import CIFAR10Worker

In [2]:
params = {'epoch_num': 10,
          'log_interval': 1250}
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [3]:
vgg_model = VGG16bn_FIM().to(device)
vgg_model = vgg_model.to_device_child_tensors(device)
vgg_model.eval_FIM()

#filename = '1epoch_VGG16bn_p1_w0_jnb.pth'
#worker = worker.set_save_path(filename).load_chckpt()

optimizer = optim.Adam(vgg_model.parameters(), lr=0.1)
worker = CIFAR10Worker(device, vgg_model, _, params)
worker = worker.load_data_loader()

Files already downloaded and verified
Files already downloaded and verified


In [5]:
worker.model.logvars

Parameter containing:
tensor([0.0158, 0.0158, 0.0158, 0.0158, 0.0158, 0.0158, 0.0158, 0.0158, 0.0158,
        0.0158, 0.0158, 0.0158, 0.0158], device='cuda:0', requires_grad=True)

In [8]:
worker.model.features[1]

True

loss tensor(76069.2734, device='cuda:0', grad_fn=<AddBackward0>)
Parameter containing:
tensor([0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000, 0.1000,
        0.1000, 0.1000, 0.1000, 0.1000], device='cuda:0', requires_grad=True)
Train Epoch: 0 [0/50000 (0%)]	Loss: 9508.659180
loss tensor(2.2764, device='cuda:0', grad_fn=<AddBackward0>)
Parameter containing:
tensor([5.6618e-09, 5.6618e-09, 5.6618e-09, 5.6618e-09, 5.6618e-09, 5.6618e-09,
        5.6618e-09, 5.6618e-09, 5.6618e-09, 5.6618e-09, 5.6618e-09, 5.6618e-09,
        5.6618e-09], device='cuda:0', requires_grad=True)
loss tensor(32300.5703, device='cuda:0', grad_fn=<AddBackward0>)
Parameter containing:
tensor([-0.0670, -0.0670, -0.0670, -0.0670, -0.0670, -0.0670, -0.0670, -0.0670,
        -0.0670, -0.0670, -0.0670, -0.0670, -0.0670], device='cuda:0',
       requires_grad=True)
loss tensor(43116.8906, device='cuda:0', grad_fn=<AddBackward0>)
Parameter containing:
tensor([-0.0776, -0.0776, -0.0776, -0.0776, -0.0776, -

In [207]:
for param in optimizer.param_groups[0]['params']:
    print(param.shape)

torch.Size([64, 3, 3, 3])
torch.Size([64])
torch.Size([])
torch.Size([64])
torch.Size([64])
torch.Size([64, 64, 3, 3])
torch.Size([64])
torch.Size([])
torch.Size([64])
torch.Size([64])
torch.Size([128, 64, 3, 3])
torch.Size([128])
torch.Size([])
torch.Size([128])
torch.Size([128])
torch.Size([128, 128, 3, 3])
torch.Size([128])
torch.Size([])
torch.Size([128])
torch.Size([128])
torch.Size([256, 128, 3, 3])
torch.Size([256])
torch.Size([])
torch.Size([256])
torch.Size([256])
torch.Size([256, 256, 3, 3])
torch.Size([256])
torch.Size([])
torch.Size([256])
torch.Size([256])
torch.Size([256, 256, 3, 3])
torch.Size([256])
torch.Size([])
torch.Size([256])
torch.Size([256])
torch.Size([512, 256, 3, 3])
torch.Size([512])
torch.Size([])
torch.Size([512])
torch.Size([512])
torch.Size([512, 512, 3, 3])
torch.Size([512])
torch.Size([])
torch.Size([512])
torch.Size([512])
torch.Size([512, 512, 3, 3])
torch.Size([512])
torch.Size([])
torch.Size([512])
torch.Size([512])
torch.Size([512, 512, 3, 3])
tor

In [199]:
optimizer.param_groups[0]['params'][2].grad

tensor(1.8283e-23, device='cuda:0')

loss tensor(10570701., device='cuda:0', grad_fn=<AddBackward0>)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0',
       requires_grad=True)
None
Train Epoch: 0 [0/50000 (0%)]	Loss: 1321337.625000
loss tensor(10570701., device='cuda:0', grad_fn=<AddBackward0>)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0',
       requires_grad=True)
tensor([2.9692e+03, 6.3343e+04, 1.2669e+05, 2.5337e+05, 5.0674e+05, 1.0135e+06,
        1.0135e+06, 2.0270e+06, 4.0539e+06, 4.0539e+06, 4.0539e+06, 4.0539e+06,
        4.0539e+06], device='cuda:0')
loss tensor(10570701., device='cuda:0', grad_fn=<AddBackward0>)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0',
       requires_grad=True)
tensor([5.9384e+03, 1.2669e+05, 2.5337e+05, 5.0674e+05, 1.0135e+06, 2.0270e+06,
        2.0270e+06, 4.0539e+06, 8.1079e+06, 8.1079e+06, 8.1079e+06, 8.1079e+06,
        8.1079e+06], device='cuda:0')
loss tensor(10570701., device='cuda:0', g

In [131]:
def test_log(self, y_hat, y):
    a = torch.sum(torch.exp(self.model.logvars) - self.model.logvars - 1)
    return  a

for batch_idx, (inputs, targets) in enumerate(worker.testloader):
    if batch_idx > 1:
        break
    else:
        pass
inputs, targets = inputs.to(device), targets.to(device)

In [132]:
targets_hat = worker.model(inputs)
targets_hat

tensor([[ 0.0915, -0.0489,  0.0351,  0.0666,  0.0764, -0.1427, -0.0085, -0.0647,
          0.1438, -0.1019],
        [ 0.0475, -0.0218,  0.0975,  0.0722,  0.0923, -0.0233, -0.1336, -0.0322,
          0.1283, -0.0855],
        [ 0.0719, -0.1015, -0.0950,  0.1382, -0.0017, -0.0800,  0.0135, -0.1323,
          0.1217,  0.0301],
        [-0.0173,  0.0359,  0.0961,  0.1381, -0.1089, -0.1463,  0.0335,  0.0634,
          0.1047, -0.0094]], device='cuda:0', grad_fn=<AddmmBackward>)

In [133]:
loss = test_log(worker, targets_hat, targets)
print(loss)

tensor(9.3377, device='cuda:0', grad_fn=<SumBackward0>)


In [134]:
loss.backward()

In [138]:
worker.model.logvars

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0',
       requires_grad=True)

In [141]:
worker.model.features[1].logvar

Parameter containing:
tensor(1., device='cuda:0', requires_grad=True)

In [149]:
worker.model.features[5].logvar.grad

tensor(3.8736e-13, device='cuda:0')

In [79]:
for param in worker.model.parameters():
    if param.grad is not None:
        print(param.grad.data)

In [131]:
    def fisher_information(self, x, y):
        '''Estimate the Fisher information of the trainable parameters.
        Args:
            x: Some input samples.
            y: Some class labels.
        Returns:
            Returns the fisher information of the trainable parameters.
            The values are arranged similarly to `EwcEstimator.params()`.
        '''
        self.eval()
        h = self(x)
        l = F.log_softmax(h, dim=1)[range(y.size(0)), y]  # log-likelihood of true class
        l = l.sum()
        l.backward()
        grads = [p.grad.data.clone() for p in next(vgg_model.parameters())]
        #fisher = [(g ** 2) / len(x) for g in grads]
        return grads

In [135]:
next(vgg_model.parameters())[0].grad

In [142]:
h = vgg_model(inputs)

In [152]:
l = F.log_softmax(h, dim=1)[range(targets.size(0)), targets]
l = l.sum()

In [155]:
l.backward()

In [162]:
next(vgg_model.parameters())[0][0].grad

In [132]:
grads = fisher_information(vgg_model, inputs, targets)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  if sys.path[0] == '':


AttributeError: 'NoneType' object has no attribute 'data'

In [130]:
grads

<generator object fisher_information.<locals>.<genexpr> at 0x7f3f9003ad00>

In [114]:
vgg_model.features[1].logvar

Parameter containing:
tensor([[0.0100]], device='cuda:1', requires_grad=True)

In [89]:
vgg_model(inputs)

tensor([[-0.0121,  0.1512, -0.0713,  0.0835, -0.0545,  0.0224, -0.0582,  0.0532,
          0.0411,  0.2262],
        [ 0.0982,  0.0749,  0.0089,  0.1046,  0.0789, -0.0737, -0.0137,  0.1690,
         -0.1287, -0.0296],
        [ 0.0516,  0.0982,  0.0602,  0.1833, -0.0817,  0.1022,  0.0923,  0.1486,
         -0.0147,  0.0761],
        [-0.0573, -0.0073,  0.0868,  0.2082,  0.0495, -0.0235,  0.0849,  0.1598,
         -0.0837, -0.0273]], device='cuda:1', grad_fn=<AddmmBackward>)

In [90]:
vgg_model(inputs)

tensor([[ 0.0486,  0.0086, -0.0676,  0.1767, -0.1206, -0.2048,  0.0473,  0.0801,
         -0.0410,  0.0811],
        [-0.1244,  0.1539, -0.0604,  0.1329, -0.0943,  0.0711, -0.0596,  0.0191,
         -0.0100,  0.0709],
        [-0.0457,  0.0104,  0.1206,  0.1887, -0.1184,  0.1160,  0.0257, -0.0554,
         -0.1523,  0.0081],
        [ 0.0287,  0.0980,  0.0581,  0.2803, -0.2386,  0.0237, -0.0017,  0.0113,
         -0.1176, -0.0629]], device='cuda:1', grad_fn=<AddmmBackward>)